language: objective-c
osx_image: xcode9.4

env:
  global:
    - PROJECT='PieCrust.xcodeproj'
    - IOS_SCHEME='PieCrust'
    - IOS_DESTINATION='platform=iOS Simulator,name=iPhone X'

before_install:
  - brew update
  - gem install xcpretty
  - brew outdated xctool || brew upgrade xctool

script:
  - set -o pipefail
  - xcodebuild clean build test -project "$PROJECT" -scheme "$IOS_SCHEME" -destination "$IOS_DESTINATION" | xcpretty
  - bash <(curl -s https://codecov.io/bash) -cF ios -J 'PieCrust'
  - swiftlint lint
  - pod lib lint